name: Deploy to Staging and Production

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          command_timeout: 30m
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            cd ~/GreepAppConfigs/greep-websocket

            # Collect secrets into EARTHLY_BUILD_ARGS
            export EARTHLY_BUILD_ARGS=""

            # Add secret environment variables to EARTHLY_BUILD_ARGS

            # Default secrets
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_KUBERNETES_CLUSTER_NAME=${{ secrets.AZURE_KUBERNETES_CLUSTER_NAME }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_REGISTRY_NAME=${{ secrets.AZURE_REGISTRY_NAME }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}SSH_HOST=${{ secrets.SSH_HOST }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}SSH_USER=${{ secrets.SSH_USER }},"

            # Additional secrets
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DB_HOST=${{ secrets.DB_HOST }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DB_PASSWORD=${{ secrets.DB_PASSWORD }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DB_USER=${{ secrets.DB_USER }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}APP_KEY=${{ secrets.APP_KEY }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY_DEV }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID_DEV }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET_DEV }},"



            # Add general variables to EARTHLY_BUILD_ARGS

            # Default variables
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}CRD_CONTROLLER_NAME=${{ vars.CRD_CONTROLLER_NAME }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}CRD_GROUP=${{ vars.CRD_GROUP }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}CRD_KIND=${{ vars.CRD_KIND }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DOCKER_REGISTRY=${{ vars.DOCKER_REGISTRY }},"

            # Additional variables


            # Remove trailing comma (if any)
            export EARTHLY_BUILD_ARGS=$(echo $EARTHLY_BUILD_ARGS | sed 's/,$//')

            # Run earthly with the dynamically created EARTHLY_BUILD_ARGS
            earthly --no-cache +setup --envs=${{ github.ref_name }} --apptype="php" --service="greep-websocket"

            az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}

            earthly --push +build --envs=${{ github.ref_name }} --version=${{ github.run_number }}  --apptype="php" --service="greep-websocket"

            # Deploy using the EARTHLY_BUILD_ARGS
            earthly --no-cache +deploy --envs=${{ github.ref_name }} --version=${{ github.run_number }}  --apptype="php" --service="greep-websocket"

  deploy-production:
    if: github.ref == 'refs/heads/prod'
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          command_timeout: 30m
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            cd ~/GreepAppConfigs/greep-websocket

            # Collect secrets into EARTHLY_BUILD_ARGS
            export EARTHLY_BUILD_ARGS=""

            # Add secret environment variables to EARTHLY_BUILD_ARGS

            # Default secrets
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_KUBERNETES_CLUSTER_NAME=${{ secrets.AZURE_KUBERNETES_CLUSTER_NAME }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_REGISTRY_NAME=${{ secrets.AZURE_REGISTRY_NAME }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}SSH_HOST=${{ secrets.SSH_HOST }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}SSH_USER=${{ secrets.SSH_USER }},"

            # Additional secrets
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DB_HOST=${{ secrets.DB_HOST }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DB_PASSWORD=${{ secrets.DB_PASSWORD }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DB_USER=${{ secrets.DB_USER }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY_PROD }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID_PROD }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET_PROD }},"

            # Add general variables to EARTHLY_BUILD_ARGS

            # Default variables
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}CRD_CONTROLLER_NAME=${{ vars.CRD_CONTROLLER_NAME }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}CRD_GROUP=${{ vars.CRD_GROUP }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}CRD_KIND=${{ vars.CRD_KIND }},"
            export EARTHLY_BUILD_ARGS="${EARTHLY_BUILD_ARGS}DOCKER_REGISTRY=${{ vars.DOCKER_REGISTRY }},"

            # Additional variables


            # Remove trailing comma (if any)
            export EARTHLY_BUILD_ARGS=$(echo $EARTHLY_BUILD_ARGS | sed 's/,$//')

            # Run earthly with the dynamically created EARTHLY_BUILD_ARGS
            earthly --no-cache +setup --envs=${{ github.ref_name }} --apptype="php" --service="greep-websocket"

            az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}

            earthly --push +build --envs=${{ github.ref_name }} --version=${{ github.run_number }} --apptype="php" --service="greep-websocket" || exit 1

            # Deploy using the EARTHLY_BUILD_ARGS
            earthly --no-cache +deploy --envs=${{ github.ref_name }} --version=${{ github.run_number }}  --apptype="php" --service="greep-websocket"
